services:
  - type: web
    name: tracker-pro
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tracker-db
          property: connectionString
      - key: OPENAI_API_KEY
        value: "YOUR_OPENAI_API_KEY_HERE"
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/opt/render/.cache/puppeteer/chrome/linux-139.0.7258.138/chrome-linux64/chrome"
    healthCheckPath: /health

databases:
  - name: tracker-db
    databaseName: tracker
    user: tracker_user
    plan: free
